### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by leones55** [CarlosX/RakionLauncher#6]
man quisiera hablar con usted por cualquier red social ya que quiero que me ayude con algo si puede porfavor se lo agradeceria.

**Comment by anjemar06** [comment]
buen dia estimado ....espero no le sea molestia revivir este post.... pero mi consulta es la siguiente:  para la configuración de los archivos en que casos tendria que colocar la ip publica del servidor...o solo pongo la ip privada en todas las configuraciones ..saludos

**Comment by CarlosX** [comment]
se ingresa el url de tu sitio web. si quieres un servidor en la red local solo ingresa tu ip lan.

**Comment by anjemar06** [comment]
@CarlosX bro una consulta ya hice todoas las configuraciones ..pero me da el siguiente error cuando quiero entrar a la creacion de personaje...
![image](https://user-images.githubusercontent.com/30170809/29245603-ae94f6d6-7fa4-11e7-9c28-4fac8a17e941.png)
Alguna de que podria ser?
De antemano gracias por la ayuda

**Comment by edu99999** [comment]
Buenas a todos, hace tiempo vengo buscando como levantar un servidor de rakion, algo pequeño para jugar con unos amigos, alguien me podria guiar por favor
